{
 "title": "Servers - Resource Usage (Collectd)",
 "description": "CollectD & Graphite Server Metrics Dashboard with  CPU, Memory, IO & Disk Stats",
 "tags": [
  "collectd",
  "sre",
  "infrastructure",
  "entrypoint"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "prefix", "query": "${VAR_PREFIX}" },
   { "name": "server", "query": "$prefix.*" },
   {
    "name": "timeperiod",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Summarises", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(collectd.$server.uptime.uptime)"
    }
   ]
  },
  {
   "title": "Load Avg (5m)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "targets": [
    {
     "target": "sumSeries(collectd.$server.load.load.midterm)"
    }
   ]
  },
  {
   "title": "Max Zombies",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "target": "sumSeries(summarize(collectd.$server.processes.ps_state-zombies, '$timeperiod', 'max', false))"
    }
   ]
  },
  {
   "title": "Proc run",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "target": "sumSeries(summarize(collectd.$server.processes.ps_state-running, '$timeperiod', 'sum', false))"
    }
   ]
  },
  {
   "title": "Proc blocked",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "target": "sumSeries(collectd.$server.processes.ps_state-blocked)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "targets": [
    {
     "refCount": -1,
     "target": "asPercent(sumSeries(keepLastValue(exclude(collectd.$server.cpu.*, 'percent-idle'), INF)), #B)",
     "targetFull": "asPercent(sumSeries(keepLastValue(exclude(collectd.$server.cpu.*, 'percent-idle'), INF)), sumSeries(keepLastValue(collectd.$server.cpu.*, INF)))"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "targets": [
    {
     "refCount": -1,
     "target": "asPercent(sumSeries(keepLastValue(collectd.$server.memory.memory-used, INF)), #B)",
     "targetFull": "asPercent(sumSeries(keepLastValue(collectd.$server.memory.memory-used, INF)), sumSeries(keepLastValue(collectd.$server.memory.*, INF)))"
    }
   ]
  },
  {
   "title": "SWAP Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "targets": [
    {
     "target": "asPercent(sumSeries(keepLastValue(collectd.$server.swap.swap-{used,cached}, INF)), #B)",
     "targetFull": "asPercent(sumSeries(keepLastValue(collectd.$server.swap.swap-{used,cached}, INF)), sumSeries(keepLastValue(collectd.$server.swap.*, INF)))"
    }
   ]
  },
  {
   "title": "Disk Usage (max)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "targets": [
    {
     "refCount": -1,
     "target": "maxSeries(aliasByNode(reduce(map(group(#A, #B), 2), 'asPercent', 3, 'df_complex-used', 'total'), 1, 2))",
     "targetFull": "maxSeries(aliasByNode(reduce(map(group(aliasSub(sumSeriesWithWildcards(aliasSub(keepLastValue(collectd.$server.df-*.df_complex-{free,used}, INF), '.*[(]([^()]+)[)].*', '\\1'), 3), '(.*)', '\\1.total'), aliasSub(keepLastValue(collectd.$server.df-*.df_complex-used, INF), '.*[(]([^()]+)[)].*', '\\1')), 2), 'asPercent', 3, 'df_complex-used', 'total'), 1, 2))"
    }
   ]
  },
  {
   "title": "Disk Inode (max)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "targets": [
    {
     "target": "maxSeries(exclude(aliasByNode(reduce(map(group(#A, #B), 2), 'asPercent', 3, 'df_inodes-used', 'total'), 1, 2), 'boot'))",
     "targetFull": "maxSeries(exclude(aliasByNode(reduce(map(group(aliasSub(sumSeriesWithWildcards(aliasSub(keepLastValue(collectd.$server.df-*.df_inodes-{free,used}, INF), '.*[(]([^()]+)[)].*', '\\1'), 3), '(.*)', '\\1.total'), aliasSub(keepLastValue(collectd.$server.df-*.df_inodes-used, INF), '.*[(]([^()]+)[)].*', '\\1')), 2), 'asPercent', 3, 'df_inodes-used', 'total'), 1, 2), 'boot'))"
    }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasSub(maxSeries(scale(summarize(collectd.$server.disk-*.disk_io_time.io_time, '$timeperiod', 'max'), 0.001)), '.*disk-(\\w+).*', ' \\1')"
    }
   ]
  },
  {
   "title": "Logged users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "target": "sumSeries(collectd.$server.users.users)"
    }
   ]
  },
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(exclude(collectd.$server.cpu.*, 'idle'), '$timeperiod', 'max', false), 1, 3)"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeries(aliasByNode(collectd.$server.memory.*, 1, 3)), 1)"
    },
    {
     "target": "aliasByNode(exclude(exclude(collectd.$server.memory.*, 'free'), 'cached'), 1, 3)"
    },
    {
     "target": "aliasByNode(collectd.$server.memory.memory-free, 1, 3)"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByNode(collectd.$server.swap.*, 1, 3), 'free')"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(collectd.$server.load.load.*, '$timeperiod', 'max', false), 1, 4)"
    }
   ]
  },
  {
   "title": "Process Fork/sec Max",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(perSecond(collectd.$server.processes.fork_rate), '$timeperiod', 'max', false), 1)"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(exclude(collectd.$server.processes.ps_state-*, 'sleeping'), '$timeperiod', 'max', false), 1, 3)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(reduce(map(group(#A, #B), 2), 'asPercent', 3, 'df_complex-used', 'total'), 1, 2)",
       "targetFull": "aliasByNode(reduce(map(group(aliasSub(sumSeriesWithWildcards(aliasSub(keepLastValue(collectd.$server.df-*.df_complex-{free,used}, INF), '.*[(]([^()]+)[)].*', '\\1'), 3), '(.*)', '\\1.total'), aliasSub(keepLastValue(collectd.$server.df-*.df_complex-used, INF), '.*[(]([^()]+)[)].*', '\\1')), 2), 'asPercent', 3, 'df_complex-used', 'total'), 1, 2)"
      }
     ]
    },
    {
     "title": "Disk Inodes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(reduce(map(group(#A, #B), 2), 'asPercent', 3, 'df_inodes-used', 'total'), 1, 2)",
       "targetFull": "aliasByNode(reduce(map(group(aliasSub(sumSeriesWithWildcards(aliasSub(keepLastValue(collectd.$server.df-*.df_inodes-{free,used}, INF), '.*[(]([^()]+)[)].*', '\\1'), 3), '(.*)', '\\1.total'), aliasSub(keepLastValue(collectd.$server.df-*.df_inodes-used, INF), '.*[(]([^()]+)[)].*', '\\1')), 2), 'asPercent', 3, 'df_inodes-used', 'total'), 1, 2)"
      }
     ]
    },
    {
     "title": "Disk - Time per operation",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(summarize(collectd.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_io_time.weighted_io_time, '$timeperiod', 'max', false), 1, 2, 4)"
      },
      {
       "target": "aliasByNode(summarize(scale(collectd.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_io_time.io_time, 0.01), '$timeperiod', 'max', false), 1, 2, 4)"
      }
     ]
    },
    {
     "title": "Disk - Operations per second",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(summarize(collectd.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_ops.read, '$timeperiod', 'max', false), 1, 2, 4)"
      },
      {
       "target": "aliasByNode(summarize(collectd.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_ops.write, '$timeperiod', 'max', false), 1, 2, 4)"
      }
     ]
    },
    {
     "title": "Disk - Pending I/O requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(summarize(collectd.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.pending_operations, '$timeperiod', 'max', false), 1, 2)"
      }
     ]
    },
    {
     "title": "Disk - Merged ops",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(summarize(collectd.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_merged.read, '$timeperiod', 'max', false), 1, 2, 4)"
      },
      {
       "target": "aliasByNode(summarize(collectd.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_merged.write, '$timeperiod', 'max', false), 1, 2, 4)"
      }
     ]
    },
    {
     "title": "Disk - Time spent doing I/O",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(summarize(collectd.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_time.read, '$timeperiod', 'max', false), 1, 2, 4)"
      },
      {
       "target": "aliasByNode(summarize(collectd.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_time.write, '$timeperiod', 'max', false), 1, 2, 4)"
      }
     ]
    },
    {
     "title": "Disk - Traffic",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "aliasByNode(scale(summarize(collectd.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_octets.read, '$timeperiod', 'max', false), 8), 1, 2, 4)"
      },
      {
       "target": "aliasByNode(scale(summarize(collectd.$server.disk-{sd*,xv*,vd*,os_*,lxc_*}.disk_octets.write, '$timeperiod', 'max', false), 8), 1, 2, 4)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic/sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasByNode(summarize(scale(collectd.$server.interface-{aggr*,bond*,vlan*,eth*,ens*}.if_octets.rx, 8), '$timeperiod', 'max', false), 1, 2, 4)"
      },
      {
       "target": "aliasByNode(summarize(scale(collectd.$server.interface-{aggr*,bond0,vlan*,eth*,ens*}.if_octets.tx, 8), '$timeperiod', 'max', false), 1, 2, 4)"
      }
     ]
    },
    {
     "title": "Network Packets/sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasByNode(summarize(collectd.$server.interface-{aggr*,bond*,vlan*,eth*,ens*}.if_packets.rx, '$timeperiod', 'max', false), 1, 2, 4)"
      },
      {
       "target": "aliasByNode(summarize(collectd.$server.interface-{aggr*,bond*,vlan*,eth*,ens*}.if_packets.tx, '$timeperiod', 'max', false), 1, 2, 4)"
      }
     ]
    },
    {
     "title": "Network Errors/sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasByNode(summarize(collectd.$server.interface-{aggr*,bond*,vlan*,eth*,ens*}.if_errors.rx, '$timeperiod', 'max', false), 1, 2, 4)"
      },
      {
       "target": "aliasByNode(summarize(collectd.$server.interface-{aggr*,bond*,vlan*,eth*,ens*}.if_errors.tx, '$timeperiod', 'max', false), 1, 2, 4)"
      }
     ]
    }
   ]
  },
  {
   "title": "NTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "NTP - Offset",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(scale(aliasByNode(exclude(exclude(collectd.$server.ntpd.time_offset-*, 'time_offset-loop'), 'time_offset-error'), 1, 3), 1000), 0, 1)"
      }
     ]
    },
    {
     "title": "NTP - Error / Loop",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode(collectd.$server.ntpd.time_offset-{error,loop}, 1, 3)"
      }
     ]
    },
    {
     "title": "NTP - Sources",
     "type": "graph",
     "description": "Dispersion of sources servers",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(exclude(scale(collectd.$server.ntpd.time_dispersion*, 1000), 'loop'), 1, 3)"
      }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(summarize(collectd.$server.users.users, '$timeperiod', 'min', false), 1)"
      }
     ]
    },
    {
     "title": "Entropy",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(summarize(collectd.$server.entropy.entropy, '$timeperiod', 'min', false), 1)"
      }
     ]
    }
   ]
  }
 ]
}